---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: accuweather
  title: AccuWeather
  tags:
    - weather
    - locations
  links:
    - url: >-
        https://raw.githubusercontent.com/apis-json/artisanal/main/apis/accuweather.json
      title: APIs.json
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  providesApi:
    - accuweather-locations-api
    - accuweather-forecast-api
    - accuweather-current-conditions-api
    - accuweather-indices-api
    - accuweather-weather-alarms-api
    - accuweather-alerts-api
    - accuweather-imagery-api
    - accuweather-tropical-api
    - accuweather-translations-api
    - accuweather-minutecast-api
  dependencyOf:
    - accuweather-best-practices
    - accuweather-status
    - accuweather-terms-of-service
    - accuweather-faq
    - accuweather-plans
    - accuweather-privacy
    - accuweather-press
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-locations-api
  title: AccuWeather Locations API
  description: >-
    Get a location key for your desired location. Use the location key to
    retrieve weather data from the Forecast or Current Conditions API.
  tags:
    - weather
    - locations
  links:
    - url: 'https://developer.accuweather.com/accuweather-locations-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-locations-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-locations-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-forecast-api
  title: AccuWeather Forecast API
  description: Get forecast information for a specific location.
  tags:
    - weather
    - forecasts
  links:
    - url: 'https://developer.accuweather.com/accuweather-forecast-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-forecast-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-forecast-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-current-conditions-api
  title: AccuWeather Current Conditions API
  description: Get Current Conditions data for a specific location.
  tags:
    - weather
    - conditions
  links:
    - url: >-
        https://developer.accuweather.com/accuweather-current-conditions-api/apis
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: >-
        https://developer.accuweather.com/accuweather-current-conditions-api/apis
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-current-conditions-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-indices-api
  title: AccuWeather Indices API
  description: >-
    Get daily index values for a specific location. Index availability varies by
    location.
  tags:
    - weather
    - indices
  links:
    - url: 'https://developer.accuweather.com/accuweather-indices-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-indices-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-indices-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-weather-alarms-api
  title: AccuWeather Weather Alarms API
  description: >-
    Get Weather Alarms for a specific location. AccuWeather Weather Alarms are
    determined using the daily forecasts for a location. An alarm exists for a
    location if the forecast weather meets or exceeds specific thresholds.
  tags:
    - weather
    - alarms
  links:
    - url: 'https://developer.accuweather.com/accuweather-weather-alarms-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-weather-alarms-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-weather-alarms-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-alerts-api
  title: AccuWeather Alerts API
  description: >-
    Get severe weather alerts from official Government Meteorological Agencies
    and leading global weather alert providers.
  tags:
    - weather
    - alerts
  links:
    - url: 'https://developer.accuweather.com/accuweather-alerts-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-alerts-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-alerts-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-imagery-api
  title: AccuWeather Imagery API
  description: Get radar and satellite images.
  tags:
    - weather
    - imagery
  links:
    - url: 'https://developer.accuweather.com/accuweather-imagery-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-imagery-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-imagery-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-tropical-api
  title: AccuWeather Tropical API
  description: >-
    Get current position, past positions, and forecasts for tropical cyclones
    worldwide.
  tags:
    - weather
    - tropoical
  links:
    - url: 'https://developer.accuweather.com/accuweather-tropical-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-tropical-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-tropical-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-translations-api
  title: AccuWeather Translations API
  description: >-
    Get a list of available languages. Get translations for specific groups of
    phrases.
  tags:
    - weather
    - translations
  links:
    - url: 'https://developer.accuweather.com/accuweather-translations-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/accuweather-translations-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-translations-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-minutecast-api
  title: AccuWeather MinuteCast® API
  description: Get a 120-minute precipitation forecast by latitude and longitude.
  tags:
    - weather
    - forecasts
  links:
    - url: 'https://developer.accuweather.com/minutecast-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-documentation
  title: AccuWeather Documentation
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/minutecast-api/apis'
      title: Documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather-minutecast-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-best-practices
  title: AccuWeather Best Practices
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/best-practices'
      title: Best Practices
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-status
  title: AccuWeather Status
  description: Needs a description.
  links:
    - url: 'https://status.accuweather.com/'
      title: Status
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-terms-of-service
  title: AccuWeather Terms of Service
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/legal'
      title: Terms of Service
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-faq
  title: AccuWeather FAQ
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/faq-page'
      title: FAQ
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-plans
  title: AccuWeather Plans
  description: Needs a description.
  links:
    - url: 'https://developer.accuweather.com/packages'
      title: Plans
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-privacy
  title: AccuWeather Privacy
  description: Needs a description.
  links:
    - url: 'http://www.accuweather.com/en/privacy'
      title: Privacy
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accuweather-press
  title: AccuWeather Press
  description: Needs a description.
  links:
    - url: 'http://www.accuweather.com/en/press'
      title: Press
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  providesApis:
    - accuweather
