---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: twilio
  title: Twilio
  tags:
    - sms
    - voice
    - messaging
    - identity
    - verification
  links:
    - url: >-
        https://raw.githubusercontent.com/apis-json/artisanal/main/apis/twilio.json
      title: APIs.json
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  providesApi:
    - twilio-messaging-api
    - twilio-email-api
    - twilio-identity-and-verification-api
    - twilio-programmable-voice-api
    - twilio-video-api
    - twilio-accounts-api
  dependencyOf:
    - twilio-x-signup
    - twilio-x-about
    - twilio-x-support
    - twilio-x-sdks
    - twilio-x-status
    - twilio-x-change-log
    - twilio-x-blog
    - twilio-x-privacy
    - twilio-x-terms-of-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-messaging-api
  title: Twilio Messaging API
  description: >-
    Send and receive messages via SMS, MMS, WhatsApp, Facebook Messenger, and
    more through our Messaging and Conversations APIs.
  tags:
    - messaging
  links:
    - url: 'https://www.twilio.com/en-us/ahoy'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/messaging'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-messaging-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-pricing
  title: Twilio X-pricing
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/sms/pricing/us'
      title: X-pricing
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-messaging-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/yaml/twilio_messaging_v1.yaml
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-messaging-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-email-api
  title: Twilio Email API
  description: >-
    Reach customers with the Twilio SendGrid Email API for reliable email
    delivery at scale.
  tags:
    - email
  links:
    - url: 'https://www.twilio.com/en-us/sendgrid/email-api'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/sendgrid/email-api'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-email-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: ''
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-email-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-identity-and-verification-api
  title: Twilio Identity and Verification API
  description: >-
    Set up SMS or voice verifications to quickly authenticate users, fight
    fraud, and protect user accounts.
  tags:
    - verification
    - identity
  links:
    - url: 'https://www.twilio.com/en-us/trusted-activation/verify'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/trusted-activation/verify'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-identity-and-verification-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-pricing
  title: Twilio X-pricing
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/verify/pricing'
      title: X-pricing
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-identity-and-verification-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: 'http://example.com/openapi.json'
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-identity-and-verification-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-programmable-voice-api
  title: Twilio Programmable Voice API
  description: >-
    Build custom voice call experiences for your applications to reach customers
    around the world.
  tags:
    - voice
  links:
    - url: 'https://www.twilio.com/en-us/voice'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/voice'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-programmable-voice-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/yaml/twilio_voice_v1.yaml
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-programmable-voice-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-video-api
  title: Twilio Video API
  description: >-
    Twilio Video is a programmable real-time communications platform that allows
    you to add video chat functionality to your web, iOS, and Android
    applications. The platform provides APIs, SDKs, and helper tools to capture,
    distribute, record, and render high quality audio and video applications.
  tags:
    - video
  links:
    - url: 'https://www.twilio.com/docs/video'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/docs/video'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-video-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/yaml/twilio_video_v1.yaml
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-video-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: twilio-accounts-api
  title: Twilio Accounts API
  description: >-
    When you first sign up with Twilio, you have just one account, your main
    account. But you can also create more accounts... subaccounts are useful for
    things like segmenting phone numbers and usage data for your customers and
    controlling access to data.
  tags:
    - video
  links:
    - url: 'https://www.twilio.com/docs/iam/api/account'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https:/api.twilio.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-documentation
  title: Twilio X-documentation
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/docs/iam/api/account'
      title: X-documentation
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-accounts-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-openapi
  title: Twilio X-openapi
  description: Needs a description.
  links:
    - url: >-
        https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/yaml/twilio_accounts_v1.yaml
      title: X-openapi
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio-accounts-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-signup
  title: Twilio X-signup
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/try-twilio'
      title: X-signup
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-about
  title: Twilio X-about
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/company'
      title: X-about
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-support
  title: Twilio X-support
  description: Needs a description.
  links:
    - url: 'https://support.twilio.com/'
      title: X-support
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-sdks
  title: Twilio X-sdks
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/docs/libraries'
      title: X-sdks
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-status
  title: Twilio X-status
  description: Needs a description.
  links:
    - url: 'https://status.twilio.com/'
      title: X-status
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-change-log
  title: Twilio X-change-log
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/changelog'
      title: X-change-log
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-blog
  title: Twilio X-blog
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/blog'
      title: X-blog
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-privacy
  title: Twilio X-privacy
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/legal/privacy'
      title: X-privacy
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: twilio-x-terms-of-service
  title: Twilio X-terms-of-service
  description: Needs a description.
  links:
    - url: 'https://www.twilio.com/en-us/legal/tos'
      title: X-terms-of-service
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: twilio
  providesApis:
    - twilio
