---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: accuweather
  title: AccuWeather
  tags:
    - weather
    - locations
  links:
    - url: >-
        https://raw.githubusercontent.com/apis-json/artisanal/main/apis/accuweather.json
      title: APIs.json
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  providesApi:
    - accuweather-locations-api
    - accuweather-forecast-api
    - accuweather-current-conditions-api
    - accuweather-indices-api
    - accuweather-weather-alarms-api
    - accuweather-alerts-api
    - accuweather-imagery-api
    - accuweather-tropical-api
    - accuweather-translations-api
    - accuweather-minutecast-api
  dependencyOf:
    - accuweather-best-practices
    - accuweather-status
    - accuweather-terms-of-service
    - accuweather-faq
    - accuweather-plans
    - accuweather-privacy
    - accuweather-press
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accuweather-locations-api
  title: AccuWeather Locations API
  description: >-
    Get a location key for your desired location. Use the location key to
    retrieve weather data from the Forecast or Current Conditions API.
  tags:
    - weather
    - locations
  links:
    - url: 'https://developer.accuweather.com/accuweather-locations-api/apis'
      title: Human URL
      icon: dashboard
      type: apis-io
    - url: 'https://api.example.com'
      title: Base URL
      icon: dashboard
      type: apis-io
spec:
  owner: apis-io
  type: apis-json
  lifecycle: published
  system: accuweather
  definition: >-
    {"openapi":"3.0.1","info":{"title":"API","description":"Minimum viable
    OpenAPI","version":"V1"},"servers":[{"url":"https://api.example.com"}],"paths":{"/api":{"get":{"summary":"API","description":"An
    API.","operationId":"api","responses":{"200":{"description":"Success","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Response"}}}}}}}},"components":{"schemas":{"Response":{"type":"object","required":["name"],"properties":{"name":{"type":"string","description":"A
    property name."}}}}}}